### ISSUE TITLE
XML element name changes

### ISSUE THREAD

**Issue by rsdoiel** [severdia/Open-Screenplay-Format#13]
I am working on some conversion tools to various formats of screenplay plays.  I notice in OSF-2.1.xml a few elements had changed name (e.g <scene_intros> became <sceneIntros>, <scene_intro> became <sceneIntro>, <scene_times> because <sceneTimes>, <scene_time> became <sceneTime>, <tag_categories> became <tagCategories>).  Was this intended? Since this changes the elemement names and would not be backward compatible with OSF-2.0 on Sourceforge shouldn't the version number be in a 3.x series?  Sorry for so many questions. Just trying to understand intent as a I build my XML parsers in Go.

Thanks, Robert

**Comment by severdia** [comment]
Hi Robert. Yes, the element/attribute naming scheme was standardized on camel case. There was quite a bit of inconsistency before when either an underscore or just all lowercase were used.

**Comment by rsdoiel** [comment]
Thanks, I'll stiff the version before sending to the XML parse then.  All the best, Robert
